.TH "_armor_params" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_armor_params
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBrsa_buf\fP"
.br
.ti -1c
.RI "int * \fBprsa_len\fP"
.br
.ti -1c
.RI "char ** \fBerr_str\fP"
.br
.ti -1c
.RI "int * \fBcleanlen\fP"
.br
.ti -1c
.RI "const char * \fBstarts\fP"
.br
.ti -1c
.RI "const char * \fBends\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int* cleanlen"

.SS "const char* ends"

.SS "char** err_str"

.SS "int* prsa_len"

.SS "char* rsa_buf"

.SS "const char* starts"


.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
