.TH "bluepoint/bluepy/bdate.h" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bluepoint/bluepy/bdate.h
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "char * \fBbdate\fP ='Sat Jul 11 23:06:44 2015'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "char* bdate ='Sat Jul 11 23:06:44 2015'"

.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
