.TH "bluepy.bdate" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bluepy.bdate
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtoday\fP = datetime\&.now()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "today = datetime\&.now()"

.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
