.TH "bluepoint/blueutil.h" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bluepoint/blueutil.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBbluepoint_hash_file\fP (char *fname, char **err_str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* bluepoint_hash_file (char * fname, char ** err_str)"

.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
