.TH "currency/quiz Directory Reference" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
currency/quiz Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBascii\&.c\fP"
.br
.ti -1c
.RI "file \fBtest1\&.c\fP"
.br
.ti -1c
.RI "file \fBtest2\&.c\fP"
.br
.ti -1c
.RI "file \fBtest3\&.c\fP"
.br
.ti -1c
.RI "file \fBtest3t\&.c\fP"
.br
.ti -1c
.RI "file \fBtest4\&.c\fP"
.br
.ti -1c
.RI "file \fBtest5\&.c\fP"
.br
.in -1c
