.TH "currency/dibadec.c" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
currency/dibadec.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include 'diba\&.h'\fP
.br
\fC#include 'bluepoint3\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdecode\fP (char *\fBstr\fP, int len)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBpass\fP [] = '1234'"
.br
.ti -1c
.RI "\fBUCHAR\fP \fBstr\fP [4 *\fBBSIZE\fP]"
.br
.ti -1c
.RI "\fBUCHAR\fP \fBstr2\fP [4 *\fBBSIZE\fP]"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void decode (char * str, int len)"

.SS "int main (int argc, char * argv[])"

.SH "Variable Documentation"
.PP 
.SS "char pass[] = '1234'"

.SS "\fBUCHAR\fP str[4 *\fBBSIZE\fP]"

.SS "\fBUCHAR\fP str2[4 *\fBBSIZE\fP]"

.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
