.TH "transport/dibastr.c" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transport/dibastr.c
.SH SYNOPSIS
.br
.PP
\fC#include 'dibastr\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const char * \fBpub_start\fP = '\-\-\-\-\-BEGIN DIGIBANK RSA PUBLIC KEY\-\-\-\-\-'"
.br
.ti -1c
.RI "const char * \fBpub_end\fP = '\-\-\-\-\-END DIGIBANK RSA PUBLIC KEY\-\-\-\-\-'"
.br
.ti -1c
.RI "const char * \fBcomp_start\fP = '\-\-\-\-\-BEGIN DIGIBANK RSA COMPOSITE KEY\-\-\-\-\-'"
.br
.ti -1c
.RI "const char * \fBcomp_end\fP = '\-\-\-\-\-END DIGIBANK RSA COMPOSITE KEY\-\-\-\-\-'"
.br
.ti -1c
.RI "const char * \fBcyph_start\fP = '\-\-\-\-\-BEGIN DIGIBANK RSA CIPHER\-\-\-\-\-'"
.br
.ti -1c
.RI "const char * \fBcyph_end\fP = '\-\-\-\-\-END DIGIBANK RSA CIPHER\-\-\-\-\-'"
.br
.ti -1c
.RI "const char * \fBmod_start\fP = '\-\-\-\-\-BEGIN DIGIBANK PUBLIC MODULUS\-\-\-\-\-'"
.br
.ti -1c
.RI "const char * \fBmod_end\fP = '\-\-\-\-\-END DIGIBANK PUBLIC MODULUS\-\-\-\-\-'"
.br
.ti -1c
.RI "const char * \fBexp_start\fP = '\-\-\-\-\-BEGIN DIGIBANK PUBLIC EXPONENT\-\-\-\-\-'"
.br
.ti -1c
.RI "const char * \fBexp_end\fP = '\-\-\-\-\-END DIGIBANK PUBLIC EXPONENT\-\-\-\-\-'"
.br
.ti -1c
.RI "const char * \fBkeypass\fP = '12345678'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char* comp_end = '\-\-\-\-\-END DIGIBANK RSA COMPOSITE KEY\-\-\-\-\-'"

.SS "const char* comp_start = '\-\-\-\-\-BEGIN DIGIBANK RSA COMPOSITE KEY\-\-\-\-\-'"

.SS "const char* cyph_end = '\-\-\-\-\-END DIGIBANK RSA CIPHER\-\-\-\-\-'"

.SS "const char* cyph_start = '\-\-\-\-\-BEGIN DIGIBANK RSA CIPHER\-\-\-\-\-'"

.SS "const char* exp_end = '\-\-\-\-\-END DIGIBANK PUBLIC EXPONENT\-\-\-\-\-'"

.SS "const char* exp_start = '\-\-\-\-\-BEGIN DIGIBANK PUBLIC EXPONENT\-\-\-\-\-'"

.SS "const char* keypass = '12345678'"

.SS "const char* mod_end = '\-\-\-\-\-END DIGIBANK PUBLIC MODULUS\-\-\-\-\-'"

.SS "const char* mod_start = '\-\-\-\-\-BEGIN DIGIBANK PUBLIC MODULUS\-\-\-\-\-'"

.SS "const char* pub_end = '\-\-\-\-\-END DIGIBANK RSA PUBLIC KEY\-\-\-\-\-'"

.SS "const char* pub_start = '\-\-\-\-\-BEGIN DIGIBANK RSA PUBLIC KEY\-\-\-\-\-'"

.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
