.TH "transport/dump.c" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transport/dump.c
.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include 'gcrypt\&.h'\fP
.br
\fC#include 'gcry\&.h'\fP
.br
\fC#include 'gsexp\&.h'\fP
.br
\fC#include 'getpass\&.h'\fP
.br
\fC#include 'zmalloc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBkeysize\fP = 1024"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Variable Documentation"
.PP 
.SS "int keysize = 1024"

.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
