.TH "gui/sutil.py" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/sutil.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsutil\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBget_screen_wh\fP ()"
.br
.ti -1c
.RI "def \fBget_screen_xy\fP ()"
.br
.ti -1c
.RI "def \fBprint_exception\fP (xstr)"
.br
.ti -1c
.RI "def \fBmessage\fP (strx, parent=None, title=None, icon=gtk\&.MESSAGE_INFO)"
.br
.ti -1c
.RI "def \fBusleep\fP (msec)"
.br
.ti -1c
.RI "def \fBtmpname\fP (indir, template)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBdisp\fP = gtk\&.gdk\&.display_get_default()"
.br
.ti -1c
.RI "\fBscr\fP = disp\&.get_default_screen()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
