.TH "currency/dibautils.c" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
currency/dibautils.c
.SH SYNOPSIS
.br
.PP
\fC#include <stddef\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include 'diba\&.h'\fP
.br
\fC#include 'dibautils\&.h'\fP
.br
\fC#include 'bluepoint3\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBrand_str\fP (char *\fBstr\fP, int len)"
.br
.ti -1c
.RI "void \fBshow_str\fP (const char *\fBstr\fP, int len)"
.br
.ti -1c
.RI "void \fBshow_hexstr\fP (const char *\fBstr\fP, int len)"
.br
.ti -1c
.RI "int \fBparse_commad_line2\fP (char **argv, \fBopts2\fP *popts_data, char **err_str)"
.br
.ti -1c
.RI "void \fBgenrev\fP (char *\fBstr\fP, int len)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void genrev (char * str, int len)"

.SS "int parse_commad_line2 (char ** argv, \fBopts2\fP * popts_data, char ** err_str)"

.SS "void rand_str (char * str, int len)"

.SS "void show_hexstr (const char * str, int len)"

.SS "void show_str (const char * str, int len)"

.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
