.TH "MainWin" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWin
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBimgbutt\fP (self, imgfile, txt, func, win)"
.br
.ti -1c
.RI "def \fBexit_all\fP (self, area=None, win=None)"
.br
.ti -1c
.RI "def \fBnext\fP (self, org)"
.br
.ti -1c
.RI "def \fBtransact\fP (self, area, me)"
.br
.ti -1c
.RI "def \fBget_one\fP (self, area, me)"
.br
.ti -1c
.RI "def \fBshow_one\fP (self, area, me)"
.br
.ti -1c
.RI "def \fBnote_focus_in\fP (self, win, act)"
.br
.ti -1c
.RI "def \fBnote_swpage_cb\fP (self, tabx, page, num)"
.br
.ti -1c
.RI "def \fBdel_one\fP (self, area, me)"
.br
.ti -1c
.RI "def \fBabove_one\fP (self, area, me)"
.br
.ti -1c
.RI "def \fBhide_one\fP (self, area, me)"
.br
.ti -1c
.RI "def \fBdone_dlg\fP (self, dlg)"
.br
.ti -1c
.RI "def \fBsel_account\fP (self, area, me)"
.br
.ti -1c
.RI "def \fBprogress\fP (self, text)"
.br
.ti -1c
.RI "def \fBgetkeyid\fP (self, fname)"
.br
.ti -1c
.RI "def \fBunlink_noerr\fP (self, fname)"
.br
.ti -1c
.RI "def \fBcallback\fP (self, form)"
.br
.ti -1c
.RI "def \fBnew_account\fP (self, area, me)"
.br
.ti -1c
.RI "def \fBsearch\fP (self, area, me)"
.br
.ti -1c
.RI "def \fBhide_all\fP (self, area, me)"
.br
.ti -1c
.RI "def \fBhide_main\fP (self, area, me)"
.br
.ti -1c
.RI "def \fBarea_button\fP (self, area, event)"
.br
.ti -1c
.RI "def \fBtree_sel_row\fP (self, xtree)"
.br
.ti -1c
.RI "def \fBkey_press_event\fP (self, area, event)"
.br
.ti -1c
.RI "def \fBOnExit\fP (self, \fBaa\fP)"
.br
.ti -1c
.RI "def \fBhandler_tick\fP (self)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtimerx\fP"
.br
.ti -1c
.RI "\fBwindow\fP"
.br
.ti -1c
.RI "\fBnotebook\fP"
.br
.ti -1c
.RI "\fBtree\fP"
.br
.ti -1c
.RI "\fBtxt1\fP"
.br
.ti -1c
.RI "\fBaccount\fP"
.br
.ti -1c
.RI "\fBactivity\fP"
.br
.ti -1c
.RI "\fBarr2\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self)"

.SH "Member Function Documentation"
.PP 
.SS "def above_one ( self,  area,  me)"

.SS "def area_button ( self,  area,  event)"

.SS "def callback ( self,  form)"

.SS "def del_one ( self,  area,  me)"

.SS "def done_dlg ( self,  dlg)"

.SS "def exit_all ( self,  area = \fCNone\fP,  win = \fCNone\fP)"

.SS "def get_one ( self,  area,  me)"

.SS "def getkeyid ( self,  fname)"

.SS "def handler_tick ( self)"

.SS "def hide_all ( self,  area,  me)"

.SS "def hide_main ( self,  area,  me)"

.SS "def hide_one ( self,  area,  me)"

.SS "def imgbutt ( self,  imgfile,  txt,  func,  win)"

.SS "def key_press_event ( self,  area,  event)"

.SS "def new_account ( self,  area,  me)"

.SS "def next ( self,  org)"

.SS "def note_focus_in ( self,  win,  act)"

.SS "def note_swpage_cb ( self,  tabx,  page,  num)"

.SS "def OnExit ( self,  aa)"

.SS "def progress ( self,  text)"

.SS "def search ( self,  area,  me)"

.SS "def sel_account ( self,  area,  me)"

.SS "def show_one ( self,  area,  me)"

.SS "def transact ( self,  area,  me)"

.SS "def tree_sel_row ( self,  xtree)"

.SS "def unlink_noerr ( self,  fname)"

.SH "Field Documentation"
.PP 
.SS "account"

.SS "activity"

.SS "arr2"

.SS "notebook"

.SS "timerx"

.SS "tree"

.SS "txt1"

.SS "window"


.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
