.TH "transport/dibaencrypt.c" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transport/dibaencrypt.c
.SH SYNOPSIS
.br
.PP
\fC#include <signal\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'gcrypt\&.h'\fP
.br
\fC#include 'gcry\&.h'\fP
.br
\fC#include 'zmalloc\&.h'\fP
.br
\fC#include 'getpass\&.h'\fP
.br
\fC#include 'base64\&.h'\fP
.br
\fC#include 'gsexp\&.h'\fP
.br
\fC#include 'cmdline\&.h'\fP
.br
\fC#include 'dibastr\&.h'\fP
.br
\fC#include 'bluepoint2\&.h'\fP
.br
\fC#include 'misc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBopts\fP \fBopts_data\fP []"
.br
.ti -1c
.RI "char \fBdescstr\fP [] = 'Encrypt files with Public key\\n'"
.br
.ti -1c
.RI "char \fBusestr\fP [] = 'asencrypt [options] keyfile'"
.br
.ti -1c
.RI "char * \fBmstr\fP = 'No Memory'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Variable Documentation"
.PP 
.SS "char descstr[] = 'Encrypt files with Public key\\n'"

.SS "char* mstr = 'No Memory'"

.SS "\fBopts\fP opts_data[]"

.SS "char usestr[] = 'asencrypt [options] keyfile'"

.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
