.TH "gui/pysql.py" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/pysql.py
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBdibasql\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpysql\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBfields\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
