.TH "dibasql" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dibasql
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, file)"
.br
.ti -1c
.RI "def \fBput\fP (self, datax)"
.br
.ti -1c
.RI "def \fBgetnames\fP (self)"
.br
.ti -1c
.RI "def \fBgetcustnames\fP (self)"
.br
.ti -1c
.RI "def \fBgetall\fP (self)"
.br
.ti -1c
.RI "def \fBrmall\fP (self)"
.br
.ti -1c
.RI "def \fBrmone\fP (self, kkk)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBconn\fP"
.br
.ti -1c
.RI "\fBc\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self,  file)"

.SH "Member Function Documentation"
.PP 
.SS "def getall ( self)"

.SS "def getcustnames ( self)"

.SS "def getnames ( self)"

.SS "def put ( self,  datax)"

.SS "def rmall ( self)"

.SS "def rmone ( self,  kkk)"

.SH "Field Documentation"
.PP 
.SS "c"

.SS "conn"


.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
