.TH "bluepoint/test_blue3.c" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bluepoint/test_blue3.c
.SH SYNOPSIS
.br
.PP
\fC#include 'stdlib\&.h'\fP
.br
\fC#include 'stdio\&.h'\fP
.br
\fC#include 'string\&.h'\fP
.br
\fC#include 'bluepoint3\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEF_DUMPHEX\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBcopy\fP [128] = ''"
.br
.ti -1c
.RI "char \fBbound\fP [] = '1234'"
.br
.ti -1c
.RI "char \fBorig\fP [] = 'abcdefghijklmnopqrstuvwxyz'"
.br
.ti -1c
.RI "char \fBbound2\fP [] = '1234'"
.br
.ti -1c
.RI "char \fBpass\fP [128] = '1234'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEF_DUMPHEX   1"

.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Variable Documentation"
.PP 
.SS "char bound[] = '1234'"

.SS "char bound2[] = '1234'"

.SS "char copy[128] = ''"

.SS "char orig[] = 'abcdefghijklmnopqrstuvwxyz'"

.SS "char pass[128] = '1234'"

.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
