.TH "stickDoc" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stickDoc
.SH SYNOPSIS
.br
.PP
.PP
Inherits DrawingArea\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBpar\fP, \fBhead\fP, \fBtext\fP)"
.br
.ti -1c
.RI "def \fBarea_button\fP (self, area, event)"
.br
.ti -1c
.RI "def \fBarea_motion\fP (self, area, event)"
.br
.ti -1c
.RI "def \fBkey_press_event\fP (self, text_view, event)"
.br
.ti -1c
.RI "def \fBsetfont\fP (self, fam, size)"
.br
.ti -1c
.RI "def \fBarea_expose_cb\fP (self, area, event)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBpar\fP"
.br
.ti -1c
.RI "\fBparwin\fP"
.br
.ti -1c
.RI "\fBhead\fP"
.br
.ti -1c
.RI "\fBtext\fP"
.br
.ti -1c
.RI "\fBgap\fP"
.br
.ti -1c
.RI "\fBcolormap\fP"
.br
.ti -1c
.RI "\fBfgcolor\fP"
.br
.ti -1c
.RI "\fBbgcolor\fP"
.br
.ti -1c
.RI "\fBfrcolor\fP"
.br
.ti -1c
.RI "\fBpangolayout\fP"
.br
.ti -1c
.RI "\fBex\fP"
.br
.ti -1c
.RI "\fBey\fP"
.br
.ti -1c
.RI "\fBcyy\fP"
.br
.ti -1c
.RI "\fBgc\fP"
.br
.ti -1c
.RI "\fBhh\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self,  par,  head,  text)"

.SH "Member Function Documentation"
.PP 
.SS "def area_button ( self,  area,  event)"

.SS "def area_expose_cb ( self,  area,  event)"

.SS "def area_motion ( self,  area,  event)"

.SS "def key_press_event ( self,  text_view,  event)"

.SS "def setfont ( self,  fam,  size)"

.SH "Field Documentation"
.PP 
.SS "bgcolor"

.SS "colormap"

.SS "cyy"

.SS "ex"

.SS "ey"

.SS "fgcolor"

.SS "frcolor"

.SS "gap"

.SS "gc"

.SS "head"

.SS "hh"

.SS "pangolayout"

.SS "par"

.SS "parwin"

.SS "text"


.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
