.TH "bluepoint/bluepy/__init__.py" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bluepoint/bluepy/__init__.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBbluepy\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
