.TH "_getpassx" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_getpassx
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <getpass\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBprompt\fP"
.br
.ti -1c
.RI "char * \fBprompt2\fP"
.br
.ti -1c
.RI "char * \fBpass\fP"
.br
.ti -1c
.RI "int \fBmaxlen\fP"
.br
.ti -1c
.RI "int \fBweak\fP"
.br
.ti -1c
.RI "int \fBnodouble\fP"
.br
.ti -1c
.RI "int \fBminlen\fP"
.br
.ti -1c
.RI "int \fBstrength\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int maxlen"

.SS "int minlen"

.SS "int nodouble"

.SS "char* pass"

.SS "char* prompt"

.SS "char* prompt2"

.SS "int strength"

.SS "int weak"


.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
