.TH "_opts" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_opts
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmdline\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBopt\fP"
.br
.ti -1c
.RI "char * \fBlong_opt\fP"
.br
.ti -1c
.RI "int * \fBval\fP"
.br
.ti -1c
.RI "char ** \fBstrval\fP"
.br
.ti -1c
.RI "int \fBminval\fP"
.br
.ti -1c
.RI "int \fBmaxval\fP"
.br
.ti -1c
.RI "int * \fBflag\fP"
.br
.ti -1c
.RI "char * \fBhelp\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int* flag"

.SS "char* help"

.SS "char* long_opt"

.SS "int maxval"

.SS "int minval"

.SS "char opt"

.SS "char** strval"

.SS "int* val"


.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
