.TH "custselect" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
custselect
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBListCust\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Tree View/List Store

The GtkListStore is used to store data in list form, to be used
later on by a GtkTreeView to display it. This demo builds a
simple GtkListStore and displays it. See the Stock Browser
demo for a more advanced example.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "def custselect\&.main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
