.TH "diba.h" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
diba.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFALSE\fP   0"
.br
.ti -1c
.RI "#define \fBASSERT\fP   assert"
.br
.ti -1c
.RI "#define \fBTAB\fP   9"
.br
.ti -1c
.RI "#define \fBUCHAR\fP   unsigned char"
.br
.ti -1c
.RI "#define \fBUINT\fP   unsigned int"
.br
.ti -1c
.RI "#define \fBBSIZE\fP   1024"
.br
.ti -1c
.RI "#define \fBASIZE\fP   32"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ASIZE   32"

.SS "#define ASSERT   assert"

.SS "#define BSIZE   1024"

.SS "#define FALSE   0"

.SS "#define TAB   9"

.SS "#define UCHAR   unsigned char"

.SS "#define UINT   unsigned int"

.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
