.TH "Padding" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Padding
.SH SYNOPSIS
.br
.PP
.PP
Inherits Widget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, text=None)"
.br
.ti -1c
.RI "def \fBdo_realize\fP (self)"
.br
.ti -1c
.RI "def \fBdo_unrealize\fP (self)"
.br
.ti -1c
.RI "def \fBdo_size_request\fP (self, requisition)"
.br
.ti -1c
.RI "def \fBdo_size_allocate\fP (self, \fBallocation\fP)"
.br
.ti -1c
.RI "def \fBdo_expose_event\fP (self, event)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBwindow\fP"
.br
.ti -1c
.RI "\fBallocation\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self,  text = \fCNone\fP)"

.SH "Member Function Documentation"
.PP 
.SS "def do_expose_event ( self,  event)"

.SS "def do_realize ( self)"

.SS "def do_size_allocate ( self,  allocation)"

.SS "def do_size_request ( self,  requisition)"

.SS "def do_unrealize ( self)"

.SH "Field Documentation"
.PP 
.SS "allocation"

.SS "window"


.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
