.TH "gui/padding.py" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/padding.py
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBPadding\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpadding\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBTEXT\fP = 'A GtkWidget implemented in PyGTK'"
.br
.ti -1c
.RI "int \fBBORDER_WIDTH\fP = 10"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
