.TH "pysql" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysql
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBdibasql\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBfields\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "list fields"
\fBInitial value:\fP
.PP
.nf
1 =  ['lob',  'city', 'cname', 'zip', 'freetext', 'dob', 
2         'country', 'numid', 'email2', 'county', 'phone', 'addr2',
3         'comments', 'addr1', 'phone2', 'email', 'log', 'custid' ]
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
