.TH "currency/quiz/test5.c" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
currency/quiz/test5.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTRUE\fP   (1==1)"
.br
.ti -1c
.RI "#define \fBFALSE\fP   (1==0)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBxerr2\fP (const char *msg,\&.\&.\&.)"
.br
.ti -1c
.RI "unsigned int \fBgetfsize\fP (FILE *fp)"
.br
.ti -1c
.RI "int \fBis_sane\fP (const char *txt)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBval\fP [1024]"
.br
.ti -1c
.RI "int \fBvalidx\fP = 0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FALSE   (1==0)"

.SS "#define TRUE   (1==1)"

.SH "Function Documentation"
.PP 
.SS "unsigned int getfsize (FILE * fp)"

.SS "int is_sane (const char * txt)"

.SS "int main (int argc, char * argv[])"

.SS "void xerr2 (const char * msg,  \&.\&.\&.)"

.SH "Variable Documentation"
.PP 
.SS "int val[1024]"

.SS "int validx = 0"

.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
