.TH "gui/yellow.py" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/yellow.py
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBstickList\fP"
.br
.ti -1c
.RI "class \fBstickDoc\fP"
.br
.ti -1c
.RI "class \fBstickWin\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fByellow\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBGAP\fP = 4"
.br
.ti -1c
.RI "int \fBTABSTOP\fP = 4"
.br
.ti -1c
.RI "string \fBFGCOLOR\fP = '#000000'"
.br
.ti -1c
.RI "string \fBBGCOLOR\fP = '#ffff88'"
.br
.ti -1c
.RI "string \fBFRCOLOR\fP = '#cccc00'"
.br
.ti -1c
.RI "int \fBTOPSTOP\fP = 50"
.br
.ti -1c
.RI "int \fBBUTSTOP\fP = 50"
.br
.ti -1c
.RI "\fBslist\fP = stickList()"
.br
.ti -1c
.RI "int \fBxxx\fP = 50"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
