.TH "bluepoint/blueencrypt.c" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bluepoint/blueencrypt.c
.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include 'getpass\&.h'\fP
.br
\fC#include 'base64\&.h'\fP
.br
\fC#include 'zmalloc\&.h'\fP
.br
\fC#include 'cmdline\&.h'\fP
.br
\fC#include 'bluepoint3\&.h'\fP
.br
\fC#include 'blueutil\&.h'\fP
.br
\fC#include 'misc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBxerr2\fP (const char *msg,\&.\&.\&.)"
.br
.ti -1c
.RI "char * \fBbluepoint_hash_file\fP (char *fname, char **err_str)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBopts\fP \fBopts_data\fP []"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* bluepoint_hash_file (char * fname, char ** err_str)"

.SS "int main (int argc, char ** argv)"

.SS "void xerr2 (const char * msg,  \&.\&.\&.)"

.SH "Variable Documentation"
.PP 
.SS "\fBopts\fP opts_data[]"

.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
