.TH "ListCust" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ListCust
.SH SYNOPSIS
.br
.PP
.PP
Inherits Window\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, parent, \fBdata\fP)"
.br
.ti -1c
.RI "def \fBfixed_toggled\fP (self, cell, path, model)"
.br
.ti -1c
.RI "def \fBkey_press_event\fP (self, win, event)"
.br
.ti -1c
.RI "def \fBrun\fP (self)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBdata\fP"
.br
.ti -1c
.RI "\fBok\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self,  parent,  data)"

.SH "Member Function Documentation"
.PP 
.SS "def fixed_toggled ( self,  cell,  path,  model)"

.SS "def key_press_event ( self,  win,  event)"

.SS "def run ( self)"

.SH "Field Documentation"
.PP 
.SS "data"

.SS "ok"


.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
