.TH "transport/dibastr.h" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transport/dibastr.h
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const char * \fBpub_start\fP"
.br
.ti -1c
.RI "const char * \fBpub_end\fP"
.br
.ti -1c
.RI "const char * \fBcomp_start\fP"
.br
.ti -1c
.RI "const char * \fBcomp_end\fP"
.br
.ti -1c
.RI "const char * \fBcyph_start\fP"
.br
.ti -1c
.RI "const char * \fBcyph_end\fP"
.br
.ti -1c
.RI "const char * \fBmod_start\fP"
.br
.ti -1c
.RI "const char * \fBmod_end\fP"
.br
.ti -1c
.RI "const char * \fBexp_start\fP"
.br
.ti -1c
.RI "const char * \fBexp_end\fP"
.br
.ti -1c
.RI "const char * \fBkeypass\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char* comp_end"

.SS "const char* comp_start"

.SS "const char* cyph_end"

.SS "const char* cyph_start"

.SS "const char* exp_end"

.SS "const char* exp_start"

.SS "const char* keypass"

.SS "const char* mod_end"

.SS "const char* mod_start"

.SS "const char* pub_end"

.SS "const char* pub_start"

.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
