.TH "currency/digibank.c" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
currency/digibank.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include 'bluepoint3\&.h'\fP
.br
\fC#include 'cmdline\&.h'\fP
.br
\fC#include 'misc\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEF_DUMPHEX\fP"
.br
.ti -1c
.RI "#define \fBTRUE\fP   1"
.br
.ti -1c
.RI "#define \fBFALSE\fP   0"
.br
.ti -1c
.RI "#define \fBTAB\fP   9"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEF_DUMPHEX"

.SS "#define FALSE   0"

.SS "#define TAB   9"

.SS "#define TRUE   1"

.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
