.TH "NewCust" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewCust
.SH SYNOPSIS
.br
.PP
.PP
Inherits Window\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, par, \fBcback\fP, uuid_name, datax=None)"
.br
.ti -1c
.RI "def \fBrun\fP (self)"
.br
.ti -1c
.RI "def \fBspacer\fP (self, hbox, xstr='    ', expand=False)"
.br
.ti -1c
.RI "def \fBvspacer\fP (self, vbox, xstr='     ', expand=False)"
.br
.ti -1c
.RI "def \fBclick_ok\fP (self, butt, xx)"
.br
.ti -1c
.RI "def \fBclick_can\fP (self, butt, xx)"
.br
.ti -1c
.RI "def \fBkey_press_event\fP (self, win, event)"
.br
.ti -1c
.RI "def \fBarea_button\fP (self, butt)"
.br
.ti -1c
.RI "def \fBscrolledtext\fP (self, name, body=None)"
.br
.ti -1c
.RI "def \fBentryquad\fP (self, vbox, entry1, entry2)"
.br
.ti -1c
.RI "def \fBentrypair\fP (self, vbox, labtext, labname, tip, defval=None)"
.br
.ti -1c
.RI "def \fBtextviewpair\fP (self, vbox, labtext, labname, tip, defval=None)"
.br
.ti -1c
.RI "def \fBhandler_tick\fP (self)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBcback\fP"
.br
.ti -1c
.RI "\fBok\fP"
.br
.ti -1c
.RI "\fBarr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self,  par,  cback,  uuid_name,  datax = \fCNone\fP)"

.SH "Member Function Documentation"
.PP 
.SS "def area_button ( self,  butt)"

.SS "def click_can ( self,  butt,  xx)"

.SS "def click_ok ( self,  butt,  xx)"

.SS "def entrypair ( self,  vbox,  labtext,  labname,  tip,  defval = \fCNone\fP)"

.SS "def entryquad ( self,  vbox,  entry1,  entry2)"

.SS "def handler_tick ( self)"

.SS "def key_press_event ( self,  win,  event)"

.SS "def run ( self)"

.SS "def scrolledtext ( self,  name,  body = \fCNone\fP)"

.SS "def spacer ( self,  hbox,  xstr = \fC'    '\fP,  expand = \fCFalse\fP)"

.SS "def textviewpair ( self,  vbox,  labtext,  labname,  tip,  defval = \fCNone\fP)"

.SS "def vspacer ( self,  vbox,  xstr = \fC'     '\fP,  expand = \fCFalse\fP)"

.SH "Field Documentation"
.PP 
.SS "arr"

.SS "cback"

.SS "ok"


.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
