.TH "padding" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
padding
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBPadding\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBTEXT\fP = 'A GtkWidget implemented in PyGTK'"
.br
.ti -1c
.RI "int \fBBORDER_WIDTH\fP = 10"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "int BORDER_WIDTH = 10"

.SS "string TEXT = 'A GtkWidget implemented in PyGTK'"

.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
