.TH "tools/test_base64b.c" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tools/test_base64b.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include 'zmalloc\&.h'\fP
.br
\fC#include 'base64\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBxerr2\fP (const char *msg,\&.\&.\&.)"
.br
.ti -1c
.RI "unsigned int \fBgetfsize\fP (FILE *fp)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "unsigned int getfsize (FILE * fp)"

.SS "int main (int argc, char ** argv)"

.SS "void xerr2 (const char * msg,  \&.\&.\&.)"

.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
