.TH "currency/quiz/test3.c" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
currency/quiz/test3.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBxerr2\fP (const char *msg,\&.\&.\&.)"
.br
.ti -1c
.RI "unsigned int \fBgetfsize\fP (FILE *fp)"
.br
.ti -1c
.RI "void \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBval\fP [256]"
.br
.ti -1c
.RI "int \fBvalidx\fP = 0"
.br
.ti -1c
.RI "char \fBdecval\fP [256]"
.br
.ti -1c
.RI "int \fBdecidx\fP = 0"
.br
.ti -1c
.RI "int \fBfreq\fP [256] = {0}"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "unsigned int getfsize (FILE * fp)"

.SS "void main (int argc, char * argv[])"

.SS "void xerr2 (const char * msg,  \&.\&.\&.)"

.SH "Variable Documentation"
.PP 
.SS "int decidx = 0"

.SS "char decval[256]"

.SS "int freq[256] = {0}"

.SS "int val[256]"

.SS "int validx = 0"

.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
