.TH "TreeHand" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TreeHand
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, tree_sel_row)"
.br
.ti -1c
.RI "def \fBstart_tree\fP (self)"
.br
.ti -1c
.RI "def \fBcreate_tree\fP (self, match, text=None)"
.br
.ti -1c
.RI "def \fBupdate_treestore\fP (self, text)"
.br
.ti -1c
.RI "def \fBappend_treestore\fP (self, text)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtreestore\fP"
.br
.ti -1c
.RI "\fBtree\fP"
.br
.ti -1c
.RI "\fBstree\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self,  tree_sel_row)"

.SH "Member Function Documentation"
.PP 
.SS "def append_treestore ( self,  text)"

.SS "def create_tree ( self,  match,  text = \fCNone\fP)"

.SS "def start_tree ( self)"

.SS "def update_treestore ( self,  text)"

.SH "Field Documentation"
.PP 
.SS "stree"

.SS "tree"

.SS "treestore"


.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
