.TH "stickWin" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stickWin
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBme\fP, \fBhead\fP, \fBtext\fP)"
.br
.ti -1c
.RI "def \fBarea_button\fP (self, area, event)"
.br
.ti -1c
.RI "def \fBkey_press_event\fP (self, text_view, event)"
.br
.ti -1c
.RI "def \fBinvalidate\fP (self, rect=None)"
.br
.ti -1c
.RI "def \fBOnExit\fP (self, aa, bb='')"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBhead\fP"
.br
.ti -1c
.RI "\fBme\fP"
.br
.ti -1c
.RI "\fBtext\fP"
.br
.ti -1c
.RI "\fBwindow\fP"
.br
.ti -1c
.RI "\fBsticky\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self,  me,  head,  text)"

.SH "Member Function Documentation"
.PP 
.SS "def area_button ( self,  area,  event)"

.SS "def invalidate ( self,  rect = \fCNone\fP)"

.SS "def key_press_event ( self,  text_view,  event)"

.SS "def OnExit ( self,  aa,  bb = \fC''\fP)"

.SH "Field Documentation"
.PP 
.SS "head"

.SS "me"

.SS "sticky"

.SS "text"

.SS "window"


.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
