.TH "stickList" 3 "Fri Sep 29 2017" "diba" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stickList
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBadd\fP (self, item)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBdata\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self)"

.SH "Member Function Documentation"
.PP 
.SS "def add ( self,  item)"

.SH "Field Documentation"
.PP 
.SS "data"


.SH "Author"
.PP 
Generated automatically by Doxygen for diba from the source code\&.
